version: 2
jobs:
  build:
    machine:
      services:
        - docker

    steps:
      - checkout
      - run:
          name: Build Docker image
          command: docker build -t $DOCKER_REPO:$CIRCLE_SHA1 .
      - run:
          name: Login to ECR
          command: eval $(aws ecr get-login --no-include-email --region us-east-1)
      - run:
           name: Push image to ECR
           command: docker push $DOCKER_REPO:$CIRCLE_SHA1
